language: ruby
cache: bundler
env:
  global:
  - AWS_REGION=ap-southeast-1
  - secure: KuD/eadUoKxpZDz+PmwvnZyTD4OFUOKzXkCWV6H24mikKtDFreot0sm9N9kI9LcONdlQwSTsc2eFFORJB/0mDsZaZ5q8FD1NHxd8bTlgbV13SN7w7GaVkVb+hMOxQtxKpKS/439N0DovCOkBbajTgUmQ+aqiA+ea0SKYIeq2SCagyaBOnTuDwjGxahyccLF/EuW6GvzMXD4do/18WJ7AvRAeDWTMWG3rwcIrnJ7bqBJuFJF43sUGvFNMjbw8ceQyqPH/0NxeF6VGpk/MDe+vRt98+u6rb1Eb9WS1uZRkwN5tsRNwJJ15TX9Cq7XuDvbj0on/fnLAasDhlTtB06WHw0q4O2i9pmbR/pYvS9mYVDI/iguDFQ0Va0mQNs0muP8CsvghIP8FXQCazQKEPlVDO1iMhiwQrIjWeBkascOYwKou1nT+1WcJskth65aKq8dsiDB5z4jxUAKut/Te0Y86C+jME3MZ0WSlT5gidf/dYLVguFjuacq4V3FJmt2Tmyyn9Od9dMawTKH97WEec69s1/UZvovCf1oCOANpkxpGEXjP8YPMYYOiCXMhSrciPimJMx11FtL+6hpQ2L8JzjwT7hQO9TsKVzcl8bDGLde/QBFZIJNwwkqR+rm1pBN0iKFfCuaJCc1/ennQZCxusa2UVTb3VT/rlCj2Ti7wTTDVdbI=
script:
- echo "Hello World"
deploy:
- provider: elasticbeanstalk
  region: ap-southeast-1
  app: scfm
  env: scfm-webserver
  bucket_name: deploy.ews1294.info
  on:
    branch: master
- provider: elasticbeanstalk
  region: ap-southeast-1
  app: scfm
  env: scfm-worker
  bucket_name: deploy.ews1294.info
  on:
    branch: master
