language: ruby
cache: bundler
env:
  global:
  - AWS_REGION=ap-southeast-1
  # AWS Deploy Credentials
  - secure: "QghhtS6GvcHJLTjWGeYySi1OWL48akqtqhGls8pv6tdYeMm6WEzGAlVwNOX9ngZuV9JswahFFk4Jik9DsMs63patsMhuSG1+g78wexVDzeGcEu27m3n8oTklh5QEZmmaxRMXjpFB/3A7C3xhDfNns3qr1MM2388m0HA9YEveGd5km5QHKb3ZB5Sn9jdGX8vVgT3KY1EzrNhgWywkx0aaqNWGXe9TF5XxqsxAfkYK3Q/9En9FKQGv4GAeyZoc6tMsRtGS0DCEtd2F6UiYKZ109bBm6zSzN32TlFatS33KmvMTU0YghyXwm1XT17R5OkZcjvM5K48Ckkqkx2V7boebrl2ikAvZDaSkyi+EChsHCW5rCn50cH3o8agI9KYwcfNyMojyPWJ6Plq/b622A6YAByAZ2Ggj2VncIElXAT5HPJpemyEVgdJASdlzBj4BmkbLxSZlv5TCGzfJUEtRi9txmyyAvd/3nftMpzsk/gUQwzj4zz42TOCtSch26sNTwzfH+1W33Gh+XnPlLDnMorah3tHEysMqE0B5lHBnqnibuYZXZ8RVyc0TnvLg1svoCuw5PL4OiN6Xj1oFjrUP/4qSlhAOUB4KyUzDM6no44/+g6Szl/jj7YcyUY6qEwYbd9PdpiVoKvuovbXaGDFlzG4dmTa1KgCzYtzIMGT9Pvc7jws="
script:
  - echo "Hello World"
deploy:
- provider: elasticbeanstalk
  region: ap-southeast-1
  app: scfm
  env: scfm-webserver
  bucket_name: deploy.ews1294.info
  on:
    branch: master
- provider: elasticbeanstalk
  region: ap-southeast-1
  app: scfm
  env: scfm-worker
  bucket_name: deploy.ews1294.info
  on:
    branch: master
